# Generated by Django 4.1 on 2022-09-14 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='blog_comment',
            new_name='comment_count',
        ),
    ]
