# Generated by Django 4.1 on 2022-09-14 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_blog_comment_post_comment_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='comment_count',
            new_name='blog_comment',
        ),
    ]
