# Generated by Django 4.1 on 2022-09-14 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_comment_count_post_blog_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='blog_comment',
        ),
    ]
