# Generated by Django 4.1 on 2022-09-14 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_post_blog_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='blog_comment',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
